# Generated by Django 4.1.7 on 2023-03-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('subcategory_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prime_antique.category')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=300)),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(max_length=20)),
                ('total_amount', models.IntegerField()),
                ('order_certificate', models.ImageField(max_length=200, upload_to='')),
                ('payment_status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=20)),
                ('product_image', models.ImageField(max_length=200, upload_to='')),
                ('product_desc', models.CharField(max_length=300)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('role_id', models.IntegerField()),
                ('otp', models.CharField(max_length=10, null=True)),
                ('otp_used', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='product_details',
            fields=[
                ('product_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_details_price', models.CharField(max_length=20)),
                ('product_details_qty', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.product')),
            ],
            options={
                'db_table': 'product_details',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.user'),
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.IntegerField()),
                ('payment_status', models.CharField(max_length=20)),
                ('payment_date', models.DateField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_item_date', models.DateField()),
                ('order_item_address', models.CharField(max_length=300)),
                ('order_item_qty', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.order')),
            ],
            options={
                'db_table': 'orderitem',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.user'),
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_date', models.DateField()),
                ('feedback_desc', models.CharField(max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('cart_date', models.DateField()),
                ('cart_qty', models.IntegerField()),
                ('total_amt', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prime_antique.user')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
