# Generated by Django 4.1.7 on 2023-03-12 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prime_antique', '0002_remove_order_product_id_order_item_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='product_id',
        ),
    ]
